const static_targets = [
  {
    objectTag: '100_MosheAvivBuilding',
    realImage: 'images/locations/100_MosheAvivBuilding_real.png',
    gameImage: 'images/locations/100_MosheAvivBuilding_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '102_DavidParkFountain',
    realImage: 'images/locations/102_DavidParkFountain_real.png',
    gameImage: 'images/locations/102_DavidParkFountain_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '202_UshaSchool',
    realImage: 'images/locations/202_UshaSchool_real.png',
    gameImage: 'images/locations/202_UshaSchool_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '102_ZomerSchool',
    realImage: 'images/locations/102_ZomerSchool_real.png',
    gameImage: 'images/locations/102_ZomerSchool_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '200_ShenkarCollage',
    realImage: 'images/locations/200_ShenkarCollage_real.png',
    gameImage: 'images/locations/200_ShenkarCollage_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '102_BeitHachayal',
    realImage: 'images/locations/102_BeitHachayal_real.png',
    gameImage: 'images/locations/102_BeitHachayal_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '2_RamatGanMunicipality',
    realImage: 'images/locations/2_RamatGanMunicipality_real.png',
    gameImage: 'images/locations/2_RamatGanMunicipality_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '200_CommunityCenterHarozim',
    realImage: 'images/locations/200_CommunityCenterHarozim_real.png',
    gameImage: 'images/locations/200_CommunityCenterHarozim_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '101_BialikMall',
    realImage: 'images/locations/101_BialikMall_real.png',
    gameImage: 'images/locations/101_BialikMall_gamev.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '101_BusOnStation',
    realImage: 'images/locations/101_BusOnStation_real.png',
    gameImage: 'images/locations/101_BusOnStation_game.png',
    name: '',
    address: '',
    description: '',
  },
  {
    objectTag: '2_location_monky_game',
    realImage: 'images/locations/2_location_monky_game.png',
    gameImage: 'images/locations/2_location_monky_game.png',
    name: '',
    address: '',
    description: '',
  },
];

export { static_targets };
